### ISSUE TITLE
removing `%T` in favor of an additional variable `add_timestamp`

### ISSUE THREAD

**Issue by Melkor333** [adfinis/pyaptly#122]
A simplification of the whole timestamp stuff would be to completely hide the logic from the user (and therefore also eliminate configuration errors) by having an additional flag like:
```toml
[snapshot."bookworm-main"]
mirror = "bookworm-main" 
add_timestamp = true
```

That would also mean we don't need to parse the snapshot name to see if it has timestamps.

_Originally posted by @Melkor333 in https://github.com/adfinis/pyaptly/issues/118#issuecomment-2283371826_
